// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUl2ad1zF5sh-ffZ6TiYM-qPV4b1M9318',
    appId: '1:454755295268:web:e744730100372cc34b38b1',
    messagingSenderId: '454755295268',
    projectId: 'pinterest-2026',
    authDomain: 'pinterest-2026.firebaseapp.com',
    storageBucket: 'pinterest-2026.firebasestorage.app',
    measurementId: 'G-FDL9H5M6MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbMjrksVYPX03Eu0j2vnH3uDgKJVCVfA',
    appId: '1:454755295268:android:20985ec2c13686ae4b38b1',
    messagingSenderId: '454755295268',
    projectId: 'pinterest-2026',
    storageBucket: 'pinterest-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzE5_H41GBqmUawT8rXU11nFE033g-7mA',
    appId: '1:454755295268:ios:a262f34867deaec14b38b1',
    messagingSenderId: '454755295268',
    projectId: 'pinterest-2026',
    storageBucket: 'pinterest-2026.firebasestorage.app',
    iosBundleId: 'com.example.pinterest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzE5_H41GBqmUawT8rXU11nFE033g-7mA',
    appId: '1:454755295268:ios:a262f34867deaec14b38b1',
    messagingSenderId: '454755295268',
    projectId: 'pinterest-2026',
    storageBucket: 'pinterest-2026.firebasestorage.app',
    iosBundleId: 'com.example.pinterest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUl2ad1zF5sh-ffZ6TiYM-qPV4b1M9318',
    appId: '1:454755295268:web:625e54befd7748f44b38b1',
    messagingSenderId: '454755295268',
    projectId: 'pinterest-2026',
    authDomain: 'pinterest-2026.firebaseapp.com',
    storageBucket: 'pinterest-2026.firebasestorage.app',
    measurementId: 'G-D4SVQC8B05',
  );
}
